version: "3"
services:
  backend:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map the container port to the host
      - "8001:8001"  # Map an additional port for InterpretML
    depends_on:
      - frontend  # Wait for the frontend service to start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:80"
